language: node_js
sudo: false
node_js:
  - "6.3"
script:
  - npm install
  - $GULP clean && $GULP build
  - (cd build && tar -zcf ../build.tar.gz ./*)
  - (cd build && zip -r ../build.zip ./*)
after_success:
  - git config user.name "Travis CI"
  - git config user.email "travis@example.com"
  - $GULP deploy:gh
deploy:
  provider: releases
  api_key:
    secure: gJ1p32NIh9wFggGHfaoU2dVAEo3pO8mxYvXAE6vfElIdmEEi9MLCgdm/XRVlDrPj7nPyXSQRYK2jWOtD7F/r5Or2yRVqR55RXfu9jrQIxV/k+RyDW7rwewFohdHrlfQC+Og3CIhqHDec03Q3VGZQAvTOzM2aZsBTOu3bmlxO89ii5jKwoZ92ueMLXgKFVDi52jfFZND7e0wXvTtHtHaawj6OcxIIOYBXQ8tE6psScBcqLGXC+PvKtaRoHcqjbjZNoITlqgtREEjz+xyVGVjn1is3ib0mpvCRJ7aylthit4PPfVOAzmJsR7zoJMu22pXcWKo/mKOyr/0/FKVWBTuWB1IhKYkNaznqEquCTc5wgi5ozE3LkWTxUJ4MFvbemQLVKw39VEHxmYFVl5UYz52jn8NBFCIoMzCCBd520nM/GZhLbHoUnwEtaJjg7t6wrVcXZ3Uo87ROuDrPVrDoSRNwSn2oekJpxwALuyOYo1kTl/wM97QTG+VL5H+r5PL4eUVcswtt4B/fbAS7BMvVCoTRBsmoURhGeJVnTJkprYxaJzH6Iq9Pb1E84msUW68qTR2BhGKouqxU65k2J8sYhgD/VL6HYtuLVh/lViykwYIfPU7Z5y8EG8YbwFowXAsmbTwGtekMFJL3incgl2JnVNOO+oynSDvZpDkMFBbDuRGSq2g=
  file:
    - build.zip
    - build.tar.gz
  skip_cleanup: true
  on:
    tags: true
env:
  global:
   - GULP: node_modules/gulp/bin/gulp.js
before_install:
  - openssl aes-256-cbc -K $encrypted_778b32cd91e6_key -iv $encrypted_778b32cd91e6_iv -in deploy_gh_pages.enc -out deploy_gh_pages -d
  - chmod 600 deploy_gh_pages
  - ssh-add deploy_gh_pages
